FROM payara/server-full:5.183

ADD AffinitiesNetwork/target/AffinitiesNetwork-1.0-SNAPSHOT.war /opt/payara5/glassfish/domains/domain1/autodeploy/
ADD images/payara/drivers/mysql-connector-java-5.1.39-bin.jar /glassfish4/glassfish/lib/
